[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "e35c31c73fe36af05e75b7ff530b5ede422f75a9"], # v0.54.3
    ["af923e30d1d24f1f4a4f5cb8308065173c1d9539", "0805139b8647bf6b569e555e7352182a23723f35"], # v0.55.0
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland with optional hyprbars integration."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
